/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Conexion;
import javax.swing.JOptionPane;
import negocio.Bebestible;

/**
 *
 * @author Ricardo Araya
 */
public class ActualizarBebestible extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarBebestible
     */
    public ActualizarBebestible() {
        initComponents();
        this.jText_MostrarNombre.setEnabled(false);
        this.jText_MostrarVolumen.setEnabled(false);
        this.jText_MostrarPrecio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jText_Codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jText_MostrarNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jText_MostrarVolumen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jText_MostrarPrecio = new javax.swing.JTextField();
        jB_Buscar = new javax.swing.JButton();
        jB_Salir = new javax.swing.JButton();
        jB_Actualizar = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();
        jrb_no = new javax.swing.JRadioButton();
        jrb_si = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Actualizar Bebestible");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Nombre");

        jText_MostrarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_MostrarNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Volumen");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Precio");

        jB_Buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jB_Buscar.setText("Buscar");
        jB_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BuscarActionPerformed(evt);
            }
        });

        jB_Salir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jB_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jB_Salir.setText("Salir");
        jB_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SalirActionPerformed(evt);
            }
        });

        jB_Actualizar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jB_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exchange.png"))); // NOI18N
        jB_Actualizar.setText("Actualizar");
        jB_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ActualizarActionPerformed(evt);
            }
        });

        jB_Eliminar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jB_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        jB_Eliminar.setText("Eliminar");
        jB_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EliminarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb_no);
        jrb_no.setText("No");
        jrb_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_noActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb_si);
        jrb_si.setText("Si");
        jrb_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_siActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("¿Deseas Actualizar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jB_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jB_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jText_MostrarVolumen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(jText_MostrarNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText_Codigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText_MostrarPrecio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jB_Buscar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 14, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jrb_si)
                                                .addGap(18, 18, 18)
                                                .addComponent(jrb_no))
                                            .addComponent(jLabel6))))))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jB_Buscar))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jText_MostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jText_MostrarVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_si)
                            .addComponent(jrb_no))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jText_MostrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_MostrarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_MostrarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_MostrarNombreActionPerformed

    private void jB_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BuscarActionPerformed
        
        try {
            Bebestible objBeb = new Bebestible("","",this.jText_Codigo.getText(),1);
            objBeb.cargarCodigoProducto();
            if (Conexion.buscarProducto) {
                this.jText_MostrarNombre.setText(objBeb.getNombre());
                this.jText_MostrarVolumen.setText(objBeb.getVolumen());
                this.jText_MostrarPrecio.setText(String.valueOf(objBeb.getPrecio()));
            }
            else{
                JOptionPane.showMessageDialog(null, "Bebestible no existe", "Buscando", 2);
                this.jText_MostrarNombre.setText("");
                this.jText_MostrarVolumen.setText("");
                this.jText_MostrarPrecio.setText("");
                this.jText_Codigo.setText("");
                this.jText_Codigo.requestFocus();
            }
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jB_BuscarActionPerformed

    private void jB_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_SalirActionPerformed

    private void jB_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ActualizarActionPerformed
         try {
            Bebestible objBeb = new Bebestible("","",this.jText_Codigo.getText(),1);
            objBeb.cargarCodigoProducto();
            if (Conexion.buscarProducto) {
                
               objBeb.setNombre(this.jText_MostrarNombre.getText());
               objBeb.setVolumen(this.jText_MostrarVolumen.getText());
               objBeb.setPrecio(Integer.parseInt(this.jText_MostrarPrecio.getText()));
               objBeb.actualizarBebestible();
               JOptionPane.showMessageDialog(null, "Bebestible Actualizado", "Actualizar", 2);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Bebestible no existe", "Buscando", 2);
                this.jText_MostrarNombre.setText("");
                this.jText_MostrarVolumen.setText("");
                this.jText_MostrarPrecio.setText("");
                this.jText_Codigo.setText("");
                this.jText_Codigo.requestFocus();
            }
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jB_ActualizarActionPerformed

    private void jB_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EliminarActionPerformed
        
        try {
            Bebestible objBeb = new Bebestible("","",this.jText_Codigo.getText(),1);
            objBeb.cargarCodigoProducto();
            if (Conexion.buscarProducto) {
                
                int opcion =  JOptionPane.showConfirmDialog(null, "¿Deseas Eliminar Bebestible?","Eliminar",2);
                if (opcion == 0){
                    objBeb.eliminarBebestible();
                    JOptionPane.showMessageDialog(null, "Bebestible Eliminado", "Eliminar", 2);
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Bebestible no existe", "Buscando", 2);
                this.jText_MostrarNombre.setText("");
                this.jText_MostrarVolumen.setText("");
                this.jText_MostrarPrecio.setText("");
                this.jText_Codigo.setText("");
                this.jText_Codigo.requestFocus();
            }
            
            
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jB_EliminarActionPerformed

    private void jrb_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_noActionPerformed

        this.jText_MostrarNombre.setEnabled(false);
        this.jText_MostrarVolumen.setEnabled(false);
        this.jText_MostrarPrecio.setEnabled(false);
    }//GEN-LAST:event_jrb_noActionPerformed

    private void jrb_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_siActionPerformed

        this.jText_MostrarNombre.setEnabled(true);
        this.jText_MostrarVolumen.setEnabled(true);
        this.jText_MostrarPrecio.setEnabled(true);

    }//GEN-LAST:event_jrb_siActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jB_Actualizar;
    private javax.swing.JButton jB_Buscar;
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jText_Codigo;
    private javax.swing.JTextField jText_MostrarNombre;
    private javax.swing.JTextField jText_MostrarPrecio;
    private javax.swing.JTextField jText_MostrarVolumen;
    private javax.swing.JRadioButton jrb_no;
    private javax.swing.JRadioButton jrb_si;
    // End of variables declaration//GEN-END:variables
}
