package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ricardo Araya
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    AgregarBebestible FGuardarBeb= new AgregarBebestible();
    ActualizarBebestible FActualizarBeb = new ActualizarBebestible();
    MostrarBesbestible FMostrarBeb = new MostrarBesbestible();
    AgregarCarne FGuardarCar= new AgregarCarne();
    ActualizarCarne FActualizarCar = new ActualizarCarne();
    MostrarCarne FMostrarCar = new MostrarCarne();
    AgregarVegetal FGuardarVeg= new AgregarVegetal();
    ActualizarVegetal FActualizarVeg = new ActualizarVegetal();
    MostrarVegetal FMostrarVeg = new MostrarVegetal();
    
    
    public VentanaPrincipal() {
        initComponents();
        this.add(FGuardarBeb);
        this.add(FActualizarBeb);
        this.add(FMostrarBeb);
        this.add(FGuardarCar);
        this.add(FActualizarCar);
        this.add(FMostrarCar);
        this.add(FGuardarVeg);
        this.add(FActualizarVeg);
        this.add(FMostrarVeg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMI_AgregarBeb = new javax.swing.JMenuItem();
        jMI_AgregarCar = new javax.swing.JMenuItem();
        jMI_AgregarVeg = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMI_ActualizarBeb = new javax.swing.JMenuItem();
        jMI_ActualizarCar = new javax.swing.JMenuItem();
        jMI_ActualizarVeg = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMI_MostrarBeb = new javax.swing.JMenuItem();
        jMI_MostrarCar = new javax.swing.JMenuItem();
        jMI_MostrarVeg = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenu3.setText("Agregar Producto");

        jMI_AgregarBeb.setText("Bebestible");
        jMI_AgregarBeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_AgregarBebActionPerformed(evt);
            }
        });
        jMenu3.add(jMI_AgregarBeb);

        jMI_AgregarCar.setText("Carne");
        jMI_AgregarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_AgregarCarActionPerformed(evt);
            }
        });
        jMenu3.add(jMI_AgregarCar);

        jMI_AgregarVeg.setText("Vegetal");
        jMI_AgregarVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_AgregarVegActionPerformed(evt);
            }
        });
        jMenu3.add(jMI_AgregarVeg);

        jMenu1.add(jMenu3);

        jMenu4.setText("Actualizar Productos");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMI_ActualizarBeb.setText("Bebestibles");
        jMI_ActualizarBeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ActualizarBebActionPerformed(evt);
            }
        });
        jMenu4.add(jMI_ActualizarBeb);

        jMI_ActualizarCar.setText("Carnes");
        jMI_ActualizarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ActualizarCarActionPerformed(evt);
            }
        });
        jMenu4.add(jMI_ActualizarCar);

        jMI_ActualizarVeg.setText("Vegetales");
        jMI_ActualizarVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ActualizarVegActionPerformed(evt);
            }
        });
        jMenu4.add(jMI_ActualizarVeg);

        jMenu1.add(jMenu4);

        jMenu5.setText("Mostrar Productos");

        jMI_MostrarBeb.setText("Bebestibles");
        jMI_MostrarBeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_MostrarBebActionPerformed(evt);
            }
        });
        jMenu5.add(jMI_MostrarBeb);

        jMI_MostrarCar.setText("Carnes");
        jMI_MostrarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_MostrarCarActionPerformed(evt);
            }
        });
        jMenu5.add(jMI_MostrarCar);

        jMI_MostrarVeg.setText("Vegetales");
        jMI_MostrarVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_MostrarVegActionPerformed(evt);
            }
        });
        jMenu5.add(jMI_MostrarVeg);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMI_AgregarVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_AgregarVegActionPerformed
        this.FGuardarVeg.show();                
    }//GEN-LAST:event_jMI_AgregarVegActionPerformed

    private void jMI_ActualizarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ActualizarCarActionPerformed
        this.FActualizarCar.show();
    }//GEN-LAST:event_jMI_ActualizarCarActionPerformed

    private void jMI_AgregarBebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_AgregarBebActionPerformed
        this.FGuardarBeb.show();
    }//GEN-LAST:event_jMI_AgregarBebActionPerformed

    private void jMI_AgregarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_AgregarCarActionPerformed
        this.FGuardarCar.show();
    }//GEN-LAST:event_jMI_AgregarCarActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMI_ActualizarBebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ActualizarBebActionPerformed
        this.FActualizarBeb.show();
    }//GEN-LAST:event_jMI_ActualizarBebActionPerformed

    private void jMI_ActualizarVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ActualizarVegActionPerformed
        this.FActualizarVeg.show();
    }//GEN-LAST:event_jMI_ActualizarVegActionPerformed

    private void jMI_MostrarBebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_MostrarBebActionPerformed
        this.FMostrarBeb.show();
    }//GEN-LAST:event_jMI_MostrarBebActionPerformed

    private void jMI_MostrarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_MostrarCarActionPerformed
        this.FMostrarCar.show();
    }//GEN-LAST:event_jMI_MostrarCarActionPerformed

    private void jMI_MostrarVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_MostrarVegActionPerformed
        this.FMostrarVeg.show();
    }//GEN-LAST:event_jMI_MostrarVegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMI_ActualizarBeb;
    private javax.swing.JMenuItem jMI_ActualizarCar;
    private javax.swing.JMenuItem jMI_ActualizarVeg;
    private javax.swing.JMenuItem jMI_AgregarBeb;
    private javax.swing.JMenuItem jMI_AgregarCar;
    private javax.swing.JMenuItem jMI_AgregarVeg;
    private javax.swing.JMenuItem jMI_MostrarBeb;
    private javax.swing.JMenuItem jMI_MostrarCar;
    private javax.swing.JMenuItem jMI_MostrarVeg;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
